# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=63, blank=True)),
                ('middle_name', models.CharField(max_length=63, blank=True)),
                ('last_name', models.CharField(max_length=63, blank=True)),
                ('social_security', models.CharField(max_length=63, blank=True)),
                ('date_of_birth', models.DateField()),
                ('ethnicity', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('veteran', models.BooleanField()),
                ('year_entered', models.IntegerField()),
                ('year_exited', models.IntegerField()),
                ('war_participated', models.IntegerField()),
                ('military_branch', models.IntegerField()),
                ('discharge_status', models.IntegerField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ContinuumMembers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=31)),
                ('website', models.CharField(max_length=63)),
                ('services_offered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=31), size=6)),
            ],
        ),
        migrations.CreateModel(
            name='ContinuumServices',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tag', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('disabilities_id', models.CharField(max_length=15)),
                ('information_date', models.DateField()),
                ('disability_type', models.IntegerField()),
                ('disability_response', models.IntegerField()),
                ('indefinite_and_impairs', models.IntegerField(null=True)),
                ('documentation_on_file', models.IntegerField(null=True)),
                ('receiving_services', models.IntegerField(null=True)),
                ('path_how_confirmed', models.IntegerField(null=True)),
                ('data_collection_stage', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentEducation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('employment_education_id', models.CharField(max_length=15)),
                ('information_date', models.DateField(null=True)),
                ('last_grade_completed', models.IntegerField(null=True)),
                ('school_status', models.IntegerField(null=True)),
                ('employed', models.IntegerField(null=True)),
                ('employment_type', models.IntegerField(null=True)),
                ('not_employed_reason', models.IntegerField(null=True)),
                ('data_collection_stage', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('entry_date', models.DateField()),
                ('household_id', models.CharField(max_length=15)),
                ('relationship_to_head_of_household', models.IntegerField(null=True)),
                ('residence_prior', models.IntegerField(null=True)),
                ('other_residence_prior', models.IntegerField(null=True)),
                ('residence_prior_length_of_stay', models.IntegerField(null=True)),
                ('disabling_condition', models.IntegerField(null=True)),
                ('entry_from_street_essh', models.IntegerField(null=True)),
                ('date_to_street_essh', models.DateField(null=True)),
                ('times_homeless_past_three_years', models.IntegerField(null=True)),
                ('month_homeless_past_three_years', models.IntegerField(null=True)),
                ('housing_status', models.IntegerField(null=True)),
                ('date_of_engagement', models.DateField(null=True)),
                ('in_permanent_housing', models.NullBooleanField()),
                ('residential_move_in_date', models.DateField(null=True)),
                ('date_of_path_status', models.DateField(null=True)),
                ('client_enrolled_in_path', models.NullBooleanField()),
                ('reason_not_enrolled', models.IntegerField(null=True)),
                ('worst_housing_situation', models.IntegerField(null=True)),
                ('percent_ami', models.IntegerField(null=True)),
                ('last_permanent_street', models.CharField(max_length=127)),
                ('last_permanent_city', models.CharField(max_length=31)),
                ('last_permanent_state', models.CharField(max_length=7)),
                ('last_permanent_zip', models.CharField(max_length=7)),
                ('date_of_bcp_status', models.DateField(null=True)),
                ('fysb_youth', models.NullBooleanField()),
                ('reason_no_services', models.IntegerField(null=True)),
                ('sexual_orientation', models.IntegerField(null=True)),
                ('formar_ward_child_welfare', models.IntegerField(null=True)),
                ('juvenile_justice_years', models.IntegerField(null=True)),
                ('juvenile_justice_months', models.IntegerField(null=True)),
                ('houshold_dynamics', models.NullBooleanField()),
                ('sexual_orientation_gender_identity_youth', models.NullBooleanField()),
                ('sexual_orientation_gender_identity_family', models.NullBooleanField()),
                ('housing_issues_youth', models.NullBooleanField()),
                ('housing_issues_family', models.NullBooleanField()),
                ('school_or_educational_issues_youth', models.NullBooleanField()),
                ('school_or_educational_issues_family', models.NullBooleanField()),
                ('unemployment_family', models.NullBooleanField()),
                ('mental_health_issues_youth', models.NullBooleanField()),
                ('mental_health_issues_family', models.NullBooleanField()),
                ('health_issues_youth', models.NullBooleanField()),
                ('health_issues_familty', models.NullBooleanField()),
                ('physical_disability_youth', models.NullBooleanField()),
                ('physical_disability_fam', models.NullBooleanField()),
                ('mental_disability_youth', models.NullBooleanField()),
                ('mental_disability_fam', models.NullBooleanField()),
                ('abuse_and_neglect_youth', models.NullBooleanField()),
                ('abuse_and_neglect_fam', models.NullBooleanField()),
                ('alcohol_drug_abuse_youth', models.NullBooleanField()),
                ('alcohol_drug_abuse_fam', models.NullBooleanField()),
                ('insufficient_income', models.NullBooleanField()),
                ('active_military_parent', models.NullBooleanField()),
                ('incarcerated_parent', models.NullBooleanField()),
                ('incarcerated_parent_status', models.IntegerField(null=True)),
                ('referral_source', models.IntegerField(null=True)),
                ('exchange_for_sex', models.IntegerField(null=True)),
                ('exchange_for_sex_past_three_months', models.IntegerField(null=True)),
                ('count_of_exchange_for_sex', models.IntegerField(null=True)),
                ('asked_or_forced_to_exchange_for_sex', models.IntegerField(null=True)),
                ('work_place_violence_threats', models.IntegerField(null=True)),
                ('work_place_promise_difference', models.IntegerField(null=True)),
                ('coerced_to_continue_work', models.IntegerField(null=True)),
                ('labor_exploit_past_three_months', models.IntegerField(null=True)),
                ('hp_screening_score', models.IntegerField(null=True)),
                ('vamc_station', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('exit_id', models.CharField(max_length=15)),
                ('destination', models.IntegerField(null=True)),
                ('other_destination', models.IntegerField(null=True)),
                ('assessment_disposition', models.IntegerField(null=True)),
                ('other_disposition', models.IntegerField(null=True)),
                ('housing_assessment', models.IntegerField(null=True)),
                ('subsidy_information', models.IntegerField(null=True)),
                ('connection_with_soar', models.IntegerField(null=True)),
                ('written_after_care_pan', models.IntegerField(null=True)),
                ('assistance_mainstream_benefits', models.IntegerField(null=True)),
                ('permanent_housing_placement', models.IntegerField(null=True)),
                ('temporary_shelter_placement', models.IntegerField(null=True)),
                ('exit_counseling', models.IntegerField(null=True)),
                ('further_follow_up_services', models.IntegerField(null=True)),
                ('scheduled_follow_up_contact', models.IntegerField(null=True)),
                ('resource_package', models.IntegerField(null=True)),
                ('other_aftercare_plan_or_action', models.IntegerField(null=True)),
                ('project_completion_status', models.IntegerField(null=True)),
                ('early_exit_reason', models.IntegerField(null=True)),
                ('family_reunification_achieved', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAndDV',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('health_and_dv_id', models.CharField(max_length=15)),
                ('information_date', models.DateField(null=True)),
                ('domestic_violence_victim', models.IntegerField(null=True)),
                ('when_occured', models.IntegerField(null=True)),
                ('currently_fleeing', models.IntegerField(null=True)),
                ('general_health_status', models.IntegerField(null=True)),
                ('dental_health_status', models.IntegerField(null=True)),
                ('mental_health_status', models.IntegerField(null=True)),
                ('pregnancy_status', models.IntegerField(null=True)),
                ('due_date', models.IntegerField(null=True)),
                ('data_collection_stage', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeBenefits',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('income_benefits_id', models.CharField(max_length=15)),
                ('information_date', models.DateField(null=True)),
                ('income_from_any_source', models.IntegerField(null=True)),
                ('total_monthly_income', models.IntegerField(null=True)),
                ('earned', models.BooleanField()),
                ('earned_amount', models.IntegerField(null=True)),
                ('unemployment', models.BooleanField()),
                ('unemployment_amount', models.IntegerField(null=True)),
                ('ssi', models.BooleanField()),
                ('ssi_amount', models.IntegerField(null=True)),
                ('ssdi', models.BooleanField()),
                ('ssdi_amount', models.IntegerField(null=True)),
                ('va_disability_service', models.BooleanField()),
                ('va_disability_service_amount', models.IntegerField(null=True)),
                ('va_disability_non_service', models.BooleanField()),
                ('va_disability_non_service_amount', models.IntegerField(null=True)),
                ('private_disability', models.BooleanField()),
                ('private_disability_amount', models.IntegerField(null=True)),
                ('workers_comp', models.BooleanField()),
                ('workers_comp_amount', models.IntegerField(null=True)),
                ('tanf', models.BooleanField()),
                ('tanf_amount', models.IntegerField(null=True)),
                ('ga', models.BooleanField()),
                ('ga_amount', models.IntegerField(null=True)),
                ('soc_sec_retirement', models.BooleanField()),
                ('soc_sec_retirement_amount', models.IntegerField(null=True)),
                ('pension', models.BooleanField()),
                ('pension_amount', models.IntegerField(null=True)),
                ('child_support', models.BooleanField()),
                ('child_support_amount', models.IntegerField(null=True)),
                ('alimony', models.BooleanField()),
                ('alimony_amount', models.IntegerField(null=True)),
                ('other_income_source', models.BooleanField()),
                ('other_incount_source_amount', models.IntegerField(null=True)),
                ('other_income_source_identify', models.CharField(max_length=126, null=True)),
                ('benefits_from_any_source', models.BooleanField()),
                ('snap', models.BooleanField()),
                ('wic', models.BooleanField()),
                ('tanf_child_care', models.BooleanField()),
                ('tanf_transportation', models.BooleanField()),
                ('other_tanf', models.BooleanField()),
                ('rental_assistance_ongoing', models.BooleanField()),
                ('rental_assistance_temp', models.BooleanField()),
                ('other_benefits_source', models.BooleanField()),
                ('other_benefits_source_identify', models.CharField(max_length=126, null=True)),
                ('insurance_from_any_source', models.NullBooleanField()),
                ('medicaid', models.BooleanField()),
                ('no_medicaid_reason', models.IntegerField(null=True)),
                ('medicare', models.BooleanField()),
                ('no_medicare_reason', models.IntegerField(null=True)),
                ('schip', models.BooleanField()),
                ('no_schip_reason', models.CharField(max_length=126, null=True)),
                ('va_medical_services', models.BooleanField()),
                ('no_va_med_reason', models.CharField(max_length=126, null=True)),
                ('employer_provided', models.BooleanField()),
                ('no_employer_provided_reason', models.CharField(max_length=126, null=True)),
                ('cobra', models.BooleanField()),
                ('no_cobra_reason', models.CharField(max_length=126, null=True)),
                ('private_pay', models.BooleanField()),
                ('no_private_pay_reason', models.CharField(max_length=126, null=True)),
                ('state_health_ins', models.BooleanField()),
                ('no_state_health_ins_reason', models.CharField(max_length=126, null=True)),
                ('hiv_aids_assistance', models.BooleanField()),
                ('no_hiv_aids_assistance_reason', models.CharField(max_length=126, null=True)),
                ('adap', models.BooleanField()),
                ('no_adap_reason', models.CharField(max_length=126, null=True)),
                ('data_collection_stage', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('personal_id', models.CharField(max_length=15)),
                ('project_entry_id', models.CharField(max_length=15)),
                ('services_id', models.CharField(max_length=15)),
                ('date_provided', models.DateField()),
                ('record_type', models.IntegerField(null=True)),
                ('type_provided', models.IntegerField(null=True)),
                ('other_type_provided', models.IntegerField(null=True)),
                ('sub_type_provided', models.IntegerField(null=True)),
                ('fa_amount', models.IntegerField(null=True)),
                ('referral_outcome', models.CharField(max_length=126)),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('associate_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=31)),
                ('address', models.CharField(max_length=63)),
                ('max_occupancy', models.IntegerField()),
                ('occupancy', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
